### ISSUE TITLE
Roadmap of release 2.0

### ISSUE THREAD

**Issue by Karnah** [Karnah/ReactiveValidation#18]
There are some new features which I would like to add in version 2.0. List can be expanding during developing.
Link to branch - [release-2.0](https://github.com/Karnah/ReactiveValidation/tree/release-2.0). If you need I can publish prerelease nuget package.

- [x] Support [Avalonia](https://github.com/AvaloniaUI/Avalonia)
     - [x] Separate Core and WPF parts, move Core part to netstandart #13 
     - [x] Check possibility of integration to Avalonia project
     - [x] Create Avalonia library and sample project
- [x] Add support for async validators
     - [x] Remove excess layer between ObjectValidator and IPropertyValitor (property adapters) #16 
     - [x] Add safe executing of async validators
- [x] Other new features
     - [x] Add possibility create validation builders in separate class. Add support of factory for this classes #14 
     - [x] Support any type of source for localized strings #15 
     - [x] Add posibility of stop validating (dispose object validator) #17 
     - [x] Add auto cast from one type to another (issue #3) 
     - [x] Add possibility for configuring custom validation template
     - [x] Add rules for validation messages: only first error message or all
- [x] Add unit tests
- [x] Add Wiki

**Comment by Karnah** [comment]
Prereleases:
Avalonia: https://www.nuget.org/packages/ReactiveValidation.Avalonia/
WPF: https://www.nuget.org/packages/ReactiveValidation.Wpf/

**Comment by Karnah** [comment]
ReactiveValidation has been finally realesed!
Avalonia: https://www.nuget.org/packages/ReactiveValidation.Avalonia/2.0.1
WPF: https://www.nuget.org/packages/ReactiveValidation.Wpf/2.0.1

I also have some ideas for future release and will create new roadmap a bit later. Thanks everybody a lot! :)
